<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mnu_CustomerPaymentsSubMenu</name>
   <tag></tag>
   <elementGuidId>6fb6a7ae-5e64-4a4f-973d-9621d348a0d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='Menu']/li[4]/div/ul/li[6]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='Menu']/li[4]/div/ul/li[6]/span</value>
   </webElementProperties>
</WebElementEntity>
