<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ApprovalsSaveButton</name>
   <tag></tag>
   <elementGuidId>1efba546-e421-4c67-93c3-968cea6639e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/form/fieldset[2]/table/tbody/tr[4]/td/input</value>
   </webElementProperties>
</WebElementEntity>
