<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_blankloanapprovals</name>
   <tag></tag>
   <elementGuidId>7ec72c0d-8ed2-4d41-a7b9-5f34ef24346e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/form/fieldset[2]/div/ul</value>
   </webElementProperties>
</WebElementEntity>
