<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verifyloanpaymentlist</name>
   <tag></tag>
   <elementGuidId>290913c5-7da4-4508-8ae7-9e18aeb8677a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='LoanPaymentPlansGrid']/table/tbody/tr[td[text()='ggg1hjkhh']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='LoanPaymentPlansGrid']/table/tbody/tr[td[text()='ggg1hjkhh']]</value>
   </webElementProperties>
</WebElementEntity>
