<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Sign_In_Button</name>
   <tag></tag>
   <elementGuidId>d2d94c50-692c-4308-9af3-da933f28b5c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divLoginFormSub&quot;)/form[1]/div[6]/input[@class=&quot;greenbutton&quot;]</value>
   </webElementProperties>
</WebElementEntity>
