<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OR-MpesaButton</name>
   <tag></tag>
   <elementGuidId>fa2da9a6-4994-48d7-87ad-fa9c623c00a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[text()=&quot;Mpesa&quot;]</value>
   </webElementProperties>
</WebElementEntity>
