<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbo_approveloan</name>
   <tag></tag>
   <elementGuidId>38bd41a5-19ae-422f-903e-28588fd8ef87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[5]/div/ul/li[text()='Approved']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[5]/div/ul/li[text()='Approved']</value>
   </webElementProperties>
</WebElementEntity>
