<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>payer</description>
   <name>chk_payer</name>
   <tag></tag>
   <elementGuidId>8ae0ec34-981d-4eb3-bbb8-04153cca5ed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='customer-input']</value>
   </webElementProperties>
</WebElementEntity>
