<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Assign</name>
   <tag></tag>
   <elementGuidId>86f3272c-b30f-48ad-ab98-cb920c67c238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/Payment/UnMatchedPayments/Assign/d5134ac0-d34b-11e7-836f-000d3ab1ec1b</value>
   </webElementProperties>
</WebElementEntity>
