<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbo_creditsystem</name>
   <tag></tag>
   <elementGuidId>eb14e31a-f466-4f3c-83fa-ebfe4543813e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/form/table/tbody/tr[8]/td[4]/div/div/span[2]/span</value>
   </webElementProperties>
</WebElementEntity>
