<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbo_credit</name>
   <tag></tag>
   <elementGuidId>7eff02d9-178f-4f94-b5c9-e511b7972322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body//li[text()=&quot;Credit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body//li[text()=&quot;Credit&quot;]</value>
   </webElementProperties>
</WebElementEntity>
