<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Assign</name>
   <tag></tag>
   <elementGuidId>86f3272c-b30f-48ad-ab98-cb920c67c238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='Payments']/table/tbody/tr[td[text()='0705572353']]/td/a[text()='Assign']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='Payments']/table/tbody/tr[td[text()='0705572353']]/td/a[text()='Assign']</value>
   </webElementProperties>
</WebElementEntity>
