<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OR-UnMatchedPayments</name>
   <tag></tag>
   <elementGuidId>4c447ecb-15ab-487e-9d85-23506a925134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='Payments']/table/tbody/tr[td[text()='0711714377']]/td/a[text()='Assign']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='Payments']/table/tbody/tr[td[text()='0711714377']]/td/a[text()='Assign']</value>
   </webElementProperties>
</WebElementEntity>
