<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbo_approvecash</name>
   <tag></tag>
   <elementGuidId>35c231b7-83ef-47f3-8f01-3f3552cfa9c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[5]/div/ul/li[text()='Approved']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[5]/div/ul/li[text()='Approved']</value>
   </webElementProperties>
</WebElementEntity>
