<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mnu_PaymentPlansSubMenu</name>
   <tag></tag>
   <elementGuidId>66144f45-45d1-472d-a01f-7c9a92ef54d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='Menu']/li[6]/div/ul/li[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='Menu']/li[6]/div/ul/li[1]/span</value>
   </webElementProperties>
</WebElementEntity>
