<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Customer_From_List_Of_Unmatched</name>
   <tag></tag>
   <elementGuidId>2b4b86c8-0fe9-4cec-8eb1-a42cbe621c2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='Payments']/table/tbody/tr[td[text()='${Refno}']]/td/a[text()='Assign']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='Payments']/table/tbody/tr[td[text()='${Refno}']]/td/a[text()='Assign']</value>
   </webElementProperties>
</WebElementEntity>
