<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectingOnReferenceDropDown</name>
   <tag></tag>
   <elementGuidId>2f06d581-1883-4f58-8cd4-ad6bf05c922f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='customer-div']/form/div[3]/div/div/span/span</value>
   </webElementProperties>
</WebElementEntity>
