<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Submenu_PaymentPlans</name>
   <tag></tag>
   <elementGuidId>8023e0ae-a258-4dd1-8421-fe47e8b813f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='Menu']/li[6]/div/ul/li[1]/span</value>
   </webElementProperties>
</WebElementEntity>
