<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>grd_productrefundscreatepayout</name>
   <tag></tag>
   <elementGuidId>d668e6e7-33ff-4475-982f-acac96fc9091</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='CustomerList']/table/tbody/tr[td[text()='26324678']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='CustomerList']/table/tbody/tr[td[text()='26324678']]</value>
   </webElementProperties>
</WebElementEntity>
