<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_paymentreceipt</name>
   <tag></tag>
   <elementGuidId>4b26bfcb-7fb9-4460-ba7b-839800aa4582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='CustomerDepositTransfers']/table/tbody/tr/td/a[text()='${depositReceipt}']</value>
   </webElementProperties>
</WebElementEntity>
