<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_approverefunds</name>
   <tag></tag>
   <elementGuidId>9e00e6fd-7a51-4c38-b837-902cc406e400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='ApprovalRefundGrid']/table/tbody/tr[td[text()='${ApproveNumber}']]/td/a[text()='Approve']</value>
   </webElementProperties>
</WebElementEntity>
