<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_approvecashpaymentplan</name>
   <tag></tag>
   <elementGuidId>2ae7f11e-386a-4e4d-9873-b67a068563e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='PaymentPlansForApprovalGrid']/table/tbody/tr[td[text()=&quot;${notes}&quot;]][td[text()=&quot;Cash&quot;]]/td/a[text()='Approve']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='PaymentPlansForApprovalGrid']/table/tbody/tr[td[text()=&quot;${notes}&quot;]][td[text()=&quot;Cash&quot;]]/td/a[text()='Approve']</value>
   </webElementProperties>
</WebElementEntity>
