<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_cashpaymentplansavebutton</name>
   <tag></tag>
   <elementGuidId>92102c05-2081-42ef-b68e-9134893888fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='divBodyMain']/form/table/tbody/tr[7]/td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/form/table/tbody/tr[7]/td/input</value>
   </webElementProperties>
</WebElementEntity>
