<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbo_ApprovalStatus</name>
   <tag></tag>
   <elementGuidId>461b8e78-62b1-4170-8174-27cabaf41d3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/form/fieldset[2]/table/tbody/tr[2]/td[2]/div/div/span[2]/span</value>
   </webElementProperties>
</WebElementEntity>
